##@S Contains code for general launcher; this makes it easier than to remember all the individual functions? 


#' General launcher function
#' 
#' @param dir Either a directory to search for files under, or a FilesDescription class object. 
#' @param mode One of (and can be abbreviations as long as its unique)
#' dependencyplot : Makes a dependency plot
#' todolist : Extracts todo list from code
#' searchcode : Searches code for 'regex', and adds 'add_comment' at all locations if set non-NULL
#' replacecode : Does looks for 'regex' and then replaces it with 'replace'. Adds 'add_comment' at all locations of replacement. 
#' clearcomments : Clears all automatically generated comments generated by searchcode and replacecode
#' documentationupdate : Generates roxygen2 documentation (and rearranges it as appropriate)
#' @param out_file File to save the output as. Only relevant for dependencyplot and todolist
#' @param regex String to search/replace for. 
#' @param add_comment String to add as comment
#' @param replace String to replace with. 
#' 
#' @return Nothing
#' 
#' @export
#' 
process_code = function(dir = NULL, mode, out_file = "test.pdf", regex = NULL, add_comment = NULL, replace = NULL) {
  
  modelist = c("dependencyplot", "todolist", "searchcode", "replacecode", "clearcomments", "documentationupdate")
  match = grep(mode, modelist)
  if (length(match) > 1) {
    stop("mode matches multiple possible modes")
  } else if (length(match) == 0) {
    stop("mode does not match any possible modes")
  }
  
  ## TODO: [Generalize] make this more extensible. 
  if (is.vector(dir)) {
    FD = FilesDescription(dirlist = dir)
  } else if (class(dir) == "FilesDescription") {
    FD = dir
  } else {
    stop ("Invalid choice for dir")
  }
  
  if (match == 1) {
    return(plot_dependency(FD = FD, out_file = out_file))
  } else if (match == 2) {
    return(generate_todolist(FD = FD))
  } else if (match == 3) {
    if (is.null(regex)) stop("regex cannot be null")
    return(search_code(RE = Regex(base = regex, isword = TRUE), add_comment = add_comment, FD = FD))
  } else if (match == 4) {
    if (is.null(regex)) stop("regex cannot be null")
    if (is.null(replace)) stop("replace cannot be null")
    return(replace_code(RE = Regex(base = regex, isword = TRUE), replace = replace, add_comment = add_comment, FD = FD))
  } else if (match == 5) {
    return(clear_comments(FD = FD))
  } else if (match == 6) {
    return(update_fx_documentation(FD = FD))
  }
}


## TODO: Idea -- write functions that examine code base for repeated patterns? (ie look for stuff that should be made into a function...)
